### ISSUE TITLE
Our build fails after upgrading to font-awesome-filetypes 1.1.0

### ISSUE THREAD

**Issue by knuterik91** [spatie/font-awesome-filetypes#4]
Hi! Our build started failing after upgrading to verison 1.1.0. 
This is the error message. 

>  mocha --compilers js:babel-register --require babel-polyfill "ClientApp/**/*.test.js"
> 
> C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\font-awesome-filetypes\lib\index.js:1
> (function (exports, require, module, __filename, __dirname) { import extensions from './extensions';
>                                                               ^^^^^^
> SyntaxError: Unexpected token import
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:542:28)
>     at Module._extensions..js (module.js:579:10)
>     at Object.require.extensions.(anonymous function) [as .js] (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\babel-register\lib\node.js:152:7)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:/projects/SequereMeProject/Onboarding/src/Web/ClientApp/EditTemplate/components/EditProcessTemplate.jsx:5:1)
>     at Module._compile (module.js:570:32)
>     at loader (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\babel-register\lib\node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .jsx] (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\babel-register\lib\node.js:154:7)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:/projects/SequereMeProject/Onboarding/src/Web/ClientApp/EditTemplate/components/editProcessTemplate.test.js:4:1)
>     at Module._compile (module.js:570:32)
>     at loader (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\babel-register\lib\node.js:144:5)
>     at Object.require.extensions.(anonymous function) [as .js] (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\babel-register\lib\node.js:154:7)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.require (module.js:497:17)
>     at require (internal/module.js:20:19)
>     at C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\mocha\lib\mocha.js:230:27
>     at Array.forEach (native)
>     at Mocha.loadFiles (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\mocha\lib\mocha.js:227:14)
>     at Mocha.run (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\mocha\lib\mocha.js:495:10)
>     at Object.<anonymous> (C:\projects\SequereMeProject\Onboarding\src\Web\node_modules\mocha\bin\_mocha:469:18)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3

this is our import statement: 
`import getClassNameForExtension from 'font-awesome-filetypes';`

and this is our code 

`getFileIcon(filename) {
        return "fa " + getClassNameForExtension(filename.split('.').pop().toLowerCase());
    }`

We have for now downgraded to version 1.0.1 that works.

**Comment by sebastiandedeyne** [comment]
I think something went wrong with the release there, `1.2.0` should resolve this issue :)
